# Auto-generated by: make init JOB=job_template
module "job_job_template" {
  source = "./modules/cloud_run_job"

  job_name              = "job-template"
  project_id            = var.project_id
  region                = var.region
  image                 = local.image
  service_account_email = google_service_account.etl_runner.email
  gcs_bucket            = var.gcs_bucket
}
