"""Scaffold a new job from the generic template."""
import shutil
import sys
from pathlib import Path


def main():
    job = sys.argv[1]
    src = Path("jobs/job_template")
    dst = Path(f"jobs/{job}")

    if dst.exists():
        print(f"Job '{job}' already exists at {dst}")
        sys.exit(1)

    shutil.copytree(src, dst)

    config_path = dst / "config.yaml"
    content = config_path.read_text()
    content = content.replace("job-template", job.replace("_", "-"))
    content = content.replace("job_template", job)
    config_path.write_text(content)

    main_path = dst / "main.py"
    content = main_path.read_text()
    content = content.replace("dataset_name", job)
    content = content.replace("table_name", job)
    main_path.write_text(content)

    _create_terraform(job)

    print(f"Job '{job}' created at {dst}")
    print(f"  Edit {dst}/main.py to implement extraction logic.")
    print(f"  Terraform file created at infra/job_{job}.tf")


def _create_terraform(job: str) -> None:
    job_hyphen = job.replace("_", "-")
    tf_path = Path(f"infra/job_{job}.tf")

    if tf_path.exists():
        print(f"  Terraform file already exists at {tf_path}, skipping.")
        return

    tf_path.write_text(
        f'# Auto-generated by: make init JOB={job}\n'
        f'module "job_{job}" {{\n'
        f'  source = "./modules/cloud_run_job"\n'
        f'\n'
        f'  job_name              = "{job_hyphen}"\n'
        f'  project_id            = var.project_id\n'
        f'  region                = var.region\n'
        f'  image                 = local.image\n'
        f'  service_account_email = google_service_account.etl_runner.email\n'
        f'  gcs_bucket            = var.gcs_bucket\n'
        f'}}\n'
    )


if __name__ == "__main__":
    main()
